=== HUnland/RunPNG/RunPNG/src/de/unlixx/runpng/resources/menusandbars.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- Common DTD for menus and bars in RunPNG --> 

<!-- Menubars and menus -->
<!ELEMENT menusandbars (menubar | contextmenu)* >
<!ELEMENT menubar (menu)* >
<!ATTLIST menubar id ID #REQUIRED >
<!ELEMENT contextmenu (separator | menuitem | dualusemenuitem)* >
<!ATTLIST contextmenu id ID #REQUIRED >
<!ELEMENT menu (separator | menuitem | dualusemenuitem)* >
<!ATTLIST menu id ID #REQUIRED >
<!ELEMENT menuitem (#PCDATA) >
<!ATTLIST menuitem
	id CDATA #REQUIRED
	icon CDATA #REQUIRED
	accel CDATA #IMPLIED
>
<!ELEMENT dualusemenuitem (#PCDATA) >
<!ATTLIST dualusemenuitem
	id CDATA #REQUIRED
	icon CDATA #REQUIRED
	id2 CDATA #REQUIRED
	icon2 CDATA #REQUIRED
	accel CDATA #IMPLIED
>

<!-- Toolbars -->
<!ELEMENT toolbars (toolbar)* >
<!ELEMENT toolbar (separator | imagebutton | dualuseimagebutton)* >
<!ATTLIST toolbar id ID #REQUIRED >
<!ELEMENT imagebutton (#PCDATA) >
<!ATTLIST imagebutton
	id CDATA #REQUIRED
	icon CDATA #REQUIRED
	tooltip CDATA #IMPLIED
>
<!ELEMENT dualuseimagebutton (#PCDATA) >
<!ATTLIST dualuseimagebutton
	id CDATA #REQUIRED
	icon CDATA #REQUIRED
	id2 CDATA #REQUIRED
	icon2 CDATA #REQUIRED
	tooltip CDATA #IMPLIED
	tooltip2 CDATA #IMPLIED
>

<!-- Commonly used -->
<!ELEMENT separator EMPTY >

=== HUnland/RunPNG/RunPNG/src/de/unlixx/runpng/resources/menusandbars.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menusandbars PUBLIC "-//unlixx.de//RunPNG//EN" "menusandbars.dtd">
<menusandbars>
	<menubar id="menubar.main">
		<menu id="menu.file">
			<menuitem id="menu.file.new" icon="icons/32x32/file.new.png" accel="Ctrl+N" />
			<separator />
			<menuitem id="menu.file.open" icon="icons/32x32/file.open.png" accel="Ctrl+O" />
			<menuitem id="menu.files.open" icon="icons/32x32/files.open.png" accel="Shift+Ctrl+O" />
			<separator />
			<menuitem id="menu.file.save" icon="icons/32x32/file.save.png" accel="Ctrl+S" />
			<menuitem id="menu.file.saveas" icon="icons/32x32/file.saveas.png" accel="Shift+Ctrl+S" />
			<menuitem id="menu.file.saveas.project" icon="icons/32x32/file.saveas.project.png" accel="Shift+Ctrl+P" />
		</menu>
		<menu id="menu.edit">
			<menuitem id="menu.edit.undo" icon="icons/32x32/edit.undo.png" accel="Ctrl+Z" />
			<menuitem id="menu.edit.redo" icon="icons/32x32/edit.redo.png" accel="Ctrl+Y" />
			<!-- <separator /> -->
		</menu>
		<menu id="menu.player">
			<menuitem id="menu.player.first" icon="icons/32x32/player.first.png" />
			<menuitem id="menu.player.prev" icon="icons/32x32/player.prev.png" />
			<dualusemenuitem id="menu.player.play" id2="menu.player.pause" icon="icons/32x32/player.play.png" icon2="icons/32x32/player.pause.png" />
			<menuitem id="menu.player.next" icon="icons/32x32/player.next.png" />
			<menuitem id="menu.player.last" icon="icons/32x32/player.last.png" />
		</menu>
		<menu id="menu.help">
			<menuitem id="menu.help.manual" icon="icons/32x32/help.manual.png" />
			<menuitem id="menu.help.about" icon="icons/32x32/help.about.png" />
		</menu>
	</menubar>
	<contextmenu id="contextmenu.frame">
		<menuitem id="menu.edit.duplicate" icon="icons/32x32/edit.duplicate.png" />
		<menuitem id="menu.edit.delete" icon="icons/32x32/edit.delete.png" />
		<separator />
		<menuitem id="menu.file.addimage" icon="icons/32x32/file.open.png" />
		<menuitem id="menu.file.saveas" icon="icons/32x32/file.saveas.png" />
	</contextmenu>
</menusandbars>

=== HUnland/RunPNG/RunPNG/src/de/unlixx/runpng/resources/toolbars.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE toolbars PUBLIC "-//unlixx.de//RunPNG//EN" "menusandbars.dtd">
<toolbars>
	<toolbar id="toolbar.main">
		<imagebutton id="menu.file.new" icon="icons/32x32/file.new.png" tooltip="tooltip.file.new" />
		<separator />
		<imagebutton id="menu.file.open" icon="icons/32x32/file.open.png" tooltip="tooltip.file.open" />
		<imagebutton id="menu.files.open" icon="icons/32x32/files.open.png" tooltip="tooltip.files.open" />
		<separator />
		<imagebutton id="menu.file.save" icon="icons/32x32/file.save.png" tooltip="tooltip.file.save" />
		<imagebutton id="menu.file.saveas" icon="icons/32x32/file.saveas.png" tooltip="tooltip.file.saveas" />
		<imagebutton id="menu.file.saveas.project" icon="icons/32x32/file.saveas.project.png" tooltip="tooltip.file.saveas.project" />
		<separator />
		<imagebutton id="menu.edit.undo" icon="icons/32x32/edit.undo.png" tooltip="tooltip.edit.undo" />
		<imagebutton id="menu.edit.redo" icon="icons/32x32/edit.redo.png" tooltip="tooltip.edit.redo" />
		<separator />
		<imagebutton id="menu.player.first" icon="icons/32x32/player.first.png" tooltip="tooltip.player.first" />
		<imagebutton id="menu.player.prev" icon="icons/32x32/player.prev.png" tooltip="tooltip.player.prev" />
		<dualuseimagebutton id="menu.player.play" id2="menu.player.pause" icon="icons/32x32/player.play.png"
				icon2="icons/32x32/player.pause.png" tooltip="tooltip.player.play" tooltip2="tooltip.player.pause" />
		<imagebutton id="menu.player.next" icon="icons/32x32/player.next.png" tooltip="tooltip.player.next" />
		<imagebutton id="menu.player.last" icon="icons/32x32/player.last.png" tooltip="tooltip.player.last" />
	</toolbar>
</toolbars>
